CREATE TABLE RITEMSXCOLOR
(
  ID INTEGER NOT NULL CONSTRAINT PK_RITEMSXCOLOR PRIMARY KEY, 
  IDITEMXCOLOR Integer NOT NULL,
  IDITEM Integer ,
  REFITEMXCOLOR Varchar(30) CHARACTER SET NONE ,
  REFINTITEMXCOLOR Varchar(10) CHARACTER SET NONE,
  NOMCOLOR Varchar(30) CHARACTER SET NONE ,
  NOMITEMXCOLORPROV Varchar(30) CHARACTER SET NONE,
  OBSERVACIONES Varchar(250) CHARACTER SET NONE,
  COLOR Varchar(30) CHARACTER SET NONE,
  CANTPEDIDA Integer,
  CANTIDAD Integer,
  CANTRESERVADA Integer,
  CANTPEDIDAPAN Integer,
  CANTRESERVADAPAN Integer,
  CANTIDADPAN Integer,
  ACTIVO Char(1) CHARACTER SET NONE ,
  AGOTADO Char(1) CHARACTER SET NONE ,
  CANTPROCESO Integer,
  ACCION CHAR(1) NOT NULL
);
CREATE GENERATOR GEN_RITEMSXCOLOR;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RITEMSXCOLOR TO  SYSDBA WITH GRANT OPTION;

SET TERM ^ ;

CREATE TRIGGER NEW_RITEMSXCOLOR FOR RITEMSXCOLOR
ACTIVE BEFORE INSERT POSITION 0
AS  
BEGIN   
    New.ID = GEN_ID(GEN_RITEMSXCOLOR,1);
END^

CREATE TRIGGER ACT_RITEMSXCOLOR FOR ITEMSXCOLOR
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0
AS  
BEGIN        
    IF (DELETING) THEN 
    BEGIN 
      INSERT INTO RITEMSXCOLOR (IdItemxColor, Accion)
           VALUES(Old.IDITEMXCOLOR, 'D');
    END 
    ELSE
    BEGIN   
        INSERT INTO RITEMSXCOLOR (IDITEMXCOLOR, IDITEM, REFITEMXCOLOR, REFINTITEMXCOLOR, NOMCOLOR, NOMITEMXCOLORPROV, OBSERVACIONES,
                                  COLOR, CANTPEDIDA, CANTIDAD, CANTRESERVADA, CANTPEDIDAPAN, CANTRESERVADAPAN, CANTIDADPAN, ACTIVO,
                                  AGOTADO, CANTPROCESO, Accion)
             SELECT New.IDITEMXCOLOR, New.IDITEM, New.REFITEMXCOLOR, New.REFINTITEMXCOLOR, New.NOMCOLOR, New.NOMITEMXCOLORPROV, New.OBSERVACIONES,
                    New.COLOR, New.CANTPEDIDA, New.CANTIDAD, New.CANTRESERVADA, New.CANTPEDIDAPAN, New.CANTRESERVADAPAN, New.CANTIDADPAN, New.ACTIVO,
                    New.AGOTADO, New.CANTPROCESO, 'I'
               FROM ITEMSXCOLOR a                
              WHERE a.IDITEMXCOLOR = New.IDITEMXCOLOR; 
    END            
END^

SET TERM ; ^ 