CREATE TABLE RITEMS
(
  ID INTEGER NOT NULL CONSTRAINT PK_RITEMS PRIMARY KEY, 
  IDITEM Integer NOT NULL,
  IDLINEA Integer,
  REFINTERNA Varchar(10) CHARACTER SET NONE,
  NOMITEM Varchar(50) CHARACTER SET NONE,
  REFPROVEEDOR Varchar(27) CHARACTER SET NONE,
  NOMITEMPROV Varchar(50) CHARACTER SET NONE,
  TIPOITEM Char(1) CHARACTER SET NONE,
  COSTOFOB decimal(18,10),
  IDMONEDA Integer,
  TIPPARTE Char(1) CHARACTER SET NONE,
  DETERMINANTE Char(1) CHARACTER SET NONE,
  OBSERVACIONES Varchar(250) CHARACTER SET NONE,
  INVENTARIOEXT Char(1) CHARACTER SET NONE,
  COSTOCIF Varchar(200) CHARACTER SET NONE,
  VOLUMEN decimal(18,10),
  PESO decimal(18,10),
  IDUNIDADFOB Integer,
  IDUNIDADCIF Integer,
  PRODNAC Char(1) CHARACTER SET NONE,
  ACTIVO Char(1) CHARACTER SET NONE,
  CATALOGOVISIBLE Char(1) CHARACTER SET NONE,  
  ACCION CHAR(1) NOT NULL
);
CREATE GENERATOR GEN_RITEMS;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RITEMS TO  SYSDBA WITH GRANT OPTION;

SET TERM ^ ;

CREATE TRIGGER NEW_RITEMS FOR RITEMS
ACTIVE BEFORE INSERT POSITION 0
AS  
BEGIN   
    New.ID = GEN_ID(GEN_RITEMS,1);
END^

CREATE TRIGGER ACT_RITEMS FOR ITEMS
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0
AS  
BEGIN        
    IF (DELETING) THEN 
    BEGIN 
      INSERT INTO RITEMS (IdItem, Accion)
           VALUES(Old.IDITEM, 'D');
    END 
    ELSE
    BEGIN   
        INSERT INTO RITEMS (IDITEM, IDLINEA, REFINTERNA, NOMITEM, REFPROVEEDOR, NOMITEMPROV,
                            TIPOITEM, COSTOFOB, IDMONEDA, TIPPARTE, DETERMINANTE, OBSERVACIONES,
                            INVENTARIOEXT, COSTOCIF, VOLUMEN, PESO, IDUNIDADFOB, IDUNIDADCIF, 
                            PRODNAC, ACTIVO, CATALOGOVISIBLE, Accion)
             SELECT New.*, 'I'
               FROM ITEMS a                
              WHERE a.IDITEM = New.IDITEM; 
    END            
END^

SET TERM ; ^ 