CREATE TABLE RMONEDAS
(
  ID INTEGER NOT NULL CONSTRAINT PK_RMONEDAS PRIMARY KEY, 
  IDMONEDA Integer NOT NULL,
  NOMMONEDA Varchar(30) CHARACTER SET NONE,
  ACCION CHAR(1) NOT NULL
);
CREATE GENERATOR GEN_RMONEDAS;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RMONEDAS TO  SYSDBA WITH GRANT OPTION;

SET TERM ^ ;

CREATE TRIGGER NEW_RMONEDAS FOR RMONEDAS
ACTIVE BEFORE INSERT POSITION 0
AS  
BEGIN   
    New.ID = GEN_ID(GEN_RMONEDAS,1);
END^

CREATE TRIGGER ACT_RMONEDAS FOR MONEDAS
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0
AS  
BEGIN        
    IF (DELETING) THEN 
    BEGIN 
      INSERT INTO RMONEDAS (IdMoneda, Accion)
           VALUES(Old.IDMONEDA, 'D');
    END 
    ELSE
    BEGIN   
        INSERT INTO RMONEDAS (IDMONEDA, NOMMONEDA, Accion)
             SELECT New.*, 'I'
               FROM MONEDAS a                
              WHERE a.IDMONEDA = New.IDMONEDA; 
    END            
END^

SET TERM ; ^ 