CREATE TABLE RUNIDADESMEDIDA
(
  ID INTEGER NOT NULL CONSTRAINT PK_RUNIDADESMEDIDA PRIMARY KEY, 
  IDUNIDAD Integer NOT NULL,
  NOMUNIDAD Varchar(30) CHARACTER SET NONE,
  ACCION CHAR(1) NOT NULL
);
CREATE GENERATOR GEN_RUNIDADESMEDIDA;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RUNIDADESMEDIDA TO  SYSDBA WITH GRANT OPTION;

SET TERM ^ ;

CREATE TRIGGER NEW_RUNIDADESMEDIDA FOR RUNIDADESMEDIDA
ACTIVE BEFORE INSERT POSITION 0
AS  
BEGIN   
    New.ID = GEN_ID(GEN_RUNIDADESMEDIDA,1);
END^

CREATE TRIGGER ACT_RUNIDADESMEDIDA FOR UNIDADESMEDIDA
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0
AS  
BEGIN        
    IF (DELETING) THEN 
    BEGIN 
      INSERT INTO RUNIDADESMEDIDA (IdUnidad, Accion)
           VALUES(Old.IDUNIDAD, 'D');
    END 
    ELSE
    BEGIN   
        INSERT INTO RUNIDADESMEDIDA (IDUNIDAD, NOMUNIDAD, Accion)
             SELECT New.*, 'I'
               FROM UNIDADESMEDIDA a                
              WHERE a.IDUNIDAD = New.IDUNIDAD; 
    END            
END^

SET TERM ; ^ 