IF OBJECT_ID('SP_BORRAR_INTEGRACION', 'P') IS NOT NULL
	DROP PROCEDURE SP_BORRAR_INTEGRACION

IF OBJECT_ID('STRANSITO', 'U') IS NOT NULL
	DROP TABLE STRANSITO

IF OBJECT_ID('REXISTENCIAS', 'U') IS NOT NULL
	DROP TABLE REXISTENCIAS

IF OBJECT_ID('RITEMSXCOLOR', 'U') IS NOT NULL
	DROP TABLE RITEMSXCOLOR

IF OBJECT_ID('RITEMS', 'U') IS NOT NULL
	DROP TABLE RITEMS

IF OBJECT_ID('RLINEAS', 'U') IS NOT NULL
	DROP TABLE RLINEAS
	
IF OBJECT_ID('RUNIDADESMEDIDA', 'U') IS NOT NULL
	DROP TABLE RUNIDADESMEDIDA
	
IF OBJECT_ID('RMONEDAS', 'U') IS NOT NULL
	DROP TABLE RMONEDAS
	
IF OBJECT_ID('REMBALAJES', 'U') IS NOT NULL
	DROP TABLE REMBALAJES
GO

CREATE TABLE RUNIDADESMEDIDA
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDUNIDAD SMALLINT NOT NULL,
  NOMUNIDAD VARCHAR(30),
  ACCION CHAR(1) NOT NULL,
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_RUNIDADESMEDIDA PRIMARY KEY (ID)
)
GO

CREATE TABLE RMONEDAS
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDMONEDA SMALLINT NOT NULL,
  NOMMONEDA VARCHAR(30),
  ACCION CHAR(1) NOT NULL,
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_RMONEDAS PRIMARY KEY (ID)
)
GO

CREATE TABLE REMBALAJES
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDEMBALAJE SMALLINT NOT NULL,
  IDITEM SMALLINT,
  PESO FLOAT,
  ALTURA FLOAT,
  ANCHO FLOAT,
  LARGO FLOAT,
  CANTIDAD VARCHAR(10),
  ACCION CHAR(1),
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_REMBALAJES PRIMARY KEY (ID)
)
GO

CREATE TABLE RLINEAS
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDLINEA SMALLINT NOT NULL,
  CODLINEA VARCHAR(10),
  NOMLINEA VARCHAR(30),
  DEMONIO CHAR(1),
  ACTIVO CHAR(1),
  ACCION CHAR(1) NOT NULL,
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_RLINEAS PRIMARY KEY (ID)
)
GO

CREATE TABLE RITEMS
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDITEM INT NOT NULL,
  IDLINEA SMALLINT,
  REFINTERNA VARCHAR(10),
  NOMITEM VARCHAR(50),
  REFPROVEEDOR VARCHAR(27),
  NOMITEMPROV VARCHAR(50),
  TIPOITEM CHAR(1) NOT NULL DEFAULT 'C',
  COSTOFOB FLOAT,
  IDMONEDA SMALLINT,
  TIPPARTE CHAR(1) NOT NULL DEFAULT 'O',
  DETERMINANTE CHAR(1) NOT NULL DEFAULT 'N',
  OBSERVACIONES VARCHAR(250),
  INVENTARIOEXT CHAR(1),
  COSTOCIF VARCHAR(200),
  VOLUMEN FLOAT,
  PESO FLOAT,
  IDUNIDADFOB SMALLINT,
  IDUNIDADCIF SMALLINT,
  PRODNAC CHAR(1),
  ACTIVO CHAR(1),
  CATALOGOVISIBLE CHAR(1),
  ACCION CHAR(1) NOT NULL,
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_RITEMS PRIMARY KEY (ID)
)
GO

CREATE TABLE RITEMSXCOLOR
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDITEMXCOLOR INT NOT NULL,
  IDITEM INT,
  REFITEMXCOLOR VARCHAR(30),
  REFINTITEMXCOLOR VARCHAR(10),
  NOMCOLOR VARCHAR(30),
  NOMITEMXCOLORPROV VARCHAR(30),
  OBSERVACIONES VARCHAR(250),
  COLOR VARCHAR(30),
  CANTPEDIDA INTEGER,
  CANTIDAD INTEGER,
  CANTRESERVADA INTEGER,
  CANTPEDIDAPAN INTEGER NOT NULL DEFAULT 0,
  CANTRESERVADAPAN INTEGER NOT NULL DEFAULT 0,
  CANTIDADPAN INTEGER NOT NULL DEFAULT 0,
  ACTIVO CHAR(1),
  AGOTADO CHAR(1),
  CANTPROCESO INTEGER,
  ACCION CHAR(1) NOT NULL,
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_RITEMSXCOLOR PRIMARY KEY (ID)
)
GO

CREATE TABLE REXISTENCIAS
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDITEMXCOLOR INT NOT NULL,
  IDITEM INT NOT NULL,
  IDBODEGA SMALLINT NOT NULL,
  COLOR VARCHAR(30) NOT NULL,
  CANTIDAD INTEGER NOT NULL,
  BODEGA VARCHAR(30) NOT NULL,
  ACCION CHAR(1) NOT NULL,
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_REXISTENCIAS PRIMARY KEY (ID)
)
GO

CREATE TABLE STRANSITO
(
  ID INTEGER NOT NULL IDENTITY(1,1),
  IDITEMTRANSITO INT NOT NULL,
  FECHAESTRECIBO DATETIME,
  CANTIDADREC INTEGER,
  FECHA DATETIME,
  ACTIVIDAD VARCHAR(200),
  IDITEMXCOLOR INT,
  ACCION CHAR(1) NOT NULL,
  INTENTOS INTEGER DEFAULT 0 NOT NULL,
  ERROR VARCHAR(MAX),
  FECHA_INTEGRA DATETIME DEFAULT GETDATE()   NOT NULL,
  CONSTRAINT PK_STRANSITO PRIMARY KEY (ID)
)
GO

CREATE PROCEDURE SP_BORRAR_INTEGRACION
	@DAYS_NUMBER INT
AS
BEGIN
	DECLARE @DATE DATETIME = DATEADD(DAY, -@DAYS_NUMBER, GETDATE());

	DELETE FROM RITEMS WHERE FECHA_INTEGRA<= @DATE;
    DELETE FROM RITEMSXCOLOR WHERE FECHA_INTEGRA<= @DATE;
    DELETE FROM RLINEAS WHERE FECHA_INTEGRA<= @DATE;
    DELETE FROM RMONEDAS WHERE FECHA_INTEGRA<= @DATE;
    DELETE FROM REMBALAJES WHERE FECHA_INTEGRA<= @DATE;
    DELETE FROM REXISTENCIAS WHERE FECHA_INTEGRA<= @DATE;
    DELETE FROM STRANSITO WHERE FECHA_INTEGRA<= @DATE;
    DELETE FROM RUNIDADESMEDIDA WHERE FECHA_INTEGRA<= @DATE; 
END
GO
