Scripts FireBird:
UPDATE ITEMSXBODEGA SET CANTIDAD = CANTIDAD + 10 WHERE IDITEMXCOLOR between 300 AND 400;
SELECT * FROM REXISTENCIAS;

UPDATE ITEMS SET NOMITEM = NOMITEM || ' (M)' WHERE IDITEM BETWEEN 50 AND 100;
SELECT * FROM RITEMS;

UPDATE ITEMSXCOLOR SET CANTIDAD = CANTIDAD + 10 WHERE IDITEMXCOLOR between 300 AND 400;
SELECT * FROM RITEMSXCOLOR;

UPDATE LINEAS SET NOMLINEA = NOMLINEA || ' (M) ' WHERE IDLINEA<20;
SELECT * FROM RLINEAS;

/*Monedas*/
select * from MONEDAS;
update monedas set nommoneda='Euro (€)' where idmoneda=13
insert into monedas (idmoneda,nommoneda) values(16,'mi moneda jling')
delete from monedas where idmoneda=16
SELECT * FROM RMONEDAS;


UPDATE UNIDADESMEDIDA SET NOMBRE = NOMBRE || ' (M)' WHERE NOMBRE ='Pieza';
SELECT * FROM RUNIDADESMEDIDA;