CREATE TABLE REXISTENCIAS
(
  ID INTEGER NOT NULL CONSTRAINT PK_REXISTENCIAS PRIMARY KEY, 
  IDITEMXCOLOR Integer NOT NULL,
  IDITEM Integer NOT NULL,
  IDBODEGA Integer NOT NULL,
  COLOR VARCHAR(30) NOT NULL,
  CANTIDAD Integer NOT NULL,
  BODEGA VARCHAR(30) NOT NULL, 
  ACCION CHAR(1) NOT NULL
);
CREATE GENERATOR GEN_REXISTENCIAS;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON REXISTENCIAS TO  SYSDBA WITH GRANT OPTION;
CREATE INDEX IND_REXISTENCIAS_1 ON REXISTENCIAS (IDITEM, COLOR, BODEGA);
CREATE INDEX IND_REXISTENCIAS_2 ON REXISTENCIAS (IDITEMXCOLOR, IDBODEGA);

SET TERM ^ ;

CREATE TRIGGER NEW_REXISTENCIAS FOR REXISTENCIAS
ACTIVE BEFORE INSERT POSITION 0
AS  
BEGIN   
    New.ID = GEN_ID(GEN_REXISTENCIAS,1);
END^

CREATE TRIGGER ACT_REXISTENCIAS FOR ITEMSXBODEGA
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0
AS  
    DECLARE Bodega VARCHAR(30);
BEGIN        
    IF (DELETING) THEN 
    BEGIN 
      INSERT INTO REXISTENCIAS (IdItemxColor, IdItem, IdBodega, Cantidad, Color, bodega, Accion)
           SELECT Old.IDITEMXCOLOR, a.IDITEM, Old.IDBODEGA, 0, 'DELETE', 'DELETE', 'D'
             FROM ITEMSXCOLOR a 
            WHERE a.IDITEMXCOLOR = old.IDITEMXCOLOR;             
    END 
    ELSE
    BEGIN
        SELECT NOMBODEGA 
          FROM BODEGAS 
         WHERE IDBODEGA = New.IDBODEGA
          INTO :Bodega;
            
        INSERT INTO REXISTENCIAS (IdItemxColor, IdItem, IdBodega, Cantidad, Color, bodega, Accion)
             SELECT New.IDITEMXCOLOR, a.IDITEM, New.IDBODEGA, New.CANTIDAD, a.NOMCOLOR, :BODEGA, 'I'
               FROM ITEMSXCOLOR a                
              WHERE a.IDITEMXCOLOR = New.IDITEMXCOLOR; 
    END            
END^

SET TERM ; ^ 