CREATE TABLE RLINEAS
(
  ID INTEGER NOT NULL CONSTRAINT PK_RLINEAS PRIMARY KEY, 
  IDLINEA Integer NOT NULL,
  CODLINEA Varchar(10) CHARACTER SET NONE,
  NOMLINEA Varchar(30) CHARACTER SET NONE,
  DEMONIO Char(1) CHARACTER SET NONE,
  ACTIVO Char(1) CHARACTER SET NONE ,
  ACCION CHAR(1) NOT NULL
);
CREATE GENERATOR GEN_RLINEAS;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON RLINEAS TO  SYSDBA WITH GRANT OPTION;

SET TERM ^ ;

CREATE TRIGGER NEW_RLINEAS FOR RLINEAS
ACTIVE BEFORE INSERT POSITION 0
AS  
BEGIN   
    New.ID = GEN_ID(GEN_RLINEAS,1);
END^

CREATE TRIGGER ACT_RLINEAS FOR LINEAS
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0
AS  
BEGIN        
    IF (DELETING) THEN 
    BEGIN 
      INSERT INTO RLINEAS (IdLinea, Accion)
           VALUES(Old.IDLINEA, 'D');
    END 
    ELSE
    BEGIN   
        INSERT INTO RLINEAS (IDLINEA, CODLINEA, NOMLINEA, DEMONIO, ACTIVO, Accion)
             SELECT New.*, 'I'
               FROM LINEAS a                
              WHERE a.IDLINEA = New.IDLINEA; 
    END            
END^

SET TERM ; ^ 